let products = [
  {
  id: 1,
  img: "/ethnic/women1.jpg",
  title: "Bridal Silk Ethnic Set",
  slug: "bridal-silk-ethnic-set",
  rating: 5.0,
  category: "ethnic",
  price: "8000",
  color: "white",
  isBestSeller: true,
  description:
    "A premium handcrafted ethnic ensemble featuring intricate embroidery and high-quality silk fabric. Perfect for weddings and festive grand occasions.",
  aosDelay: "0",
},
{
  id: 2,
  img: "/ethnic/women2.webp",
  title: "Cotton Daily Wear Suit",
  slug: "cotton-daily-wear-suit",
  rating: 5.0,
  category: "ethnic",
  price: "2000",
  color: "white",
  isBestSeller: true,
  description:
    "Elegant daily wear ethnic suit set. Lightweight cotton fabric with breathable weave, ideal for summer gatherings and office wear.",
  aosDelay: "0",
},
{
  id: 3,
  img: "/ethnic/women3.webp",
  title: "Floral Anarkali Dress",
  slug: "floral-anarkali-dress",
  rating: 5.0,
  category: "ethnic",
  price: "3000",
  color: "white",
  isBestSeller: true,
  description:
    "Stylish Anarkali style ethnic wear with floral prints. Comes with a matching dupatta and comfortable leggings for a complete look.",
  aosDelay: "0",
},
{
  id: 4,
  img: "/ethnic/women4.webp",
  title: "Gold Print Ethnic Suit",
  slug: "gold-print-ethnic-suit",
  rating: 5.0,
  category: "ethnic",
  price: "4000",
  color: "white",
  isBestSeller: false,
  description: "Classic traditional wear with a modern silhouette.",
  aosDelay: "0",
},
{
  id: 5,
  img: "/ethnic/women5.webp",
  title: "Fusion Ethnic Tunic",
  slug: "fusion-ethnic-tunic",
  rating: 5.0,
  category: "ethnic",
  price: "2000",
  color: "white",
  isBestSeller: false,
  description: "Simple yet sophisticated ethnic tunic.",
  aosDelay: "0",
},
{
  id: 6,
  img: "/ethnic/women6.jpg",
  title: "Designer Festive Wear Set",
  slug: "designer-festive-wear-set",
  rating: 5.0,
  category: "ethnic",
  price: "5000",
  color: "white",
  isBestSeller: true,
  description: "Designer festive wear set.",
  aosDelay: "0",
},

  {
  id: 7,
  img: "/western/women1.jpg",
  title: "Chic Jersey Western Top",
  slug: "chic-jersey-western-top",
  rating: 7.0,
  category: "western",
  price: "800",
  color: "white",
  isBestSeller: true,
  description: "Chic western top.",
  aosDelay: "0",
},
{
  id: 8,
  img: "/western/women2.jpg",
  title: "Pink Satin Evening Gown",
  slug: "pink-satin-evening-gown",
  rating: 5.0,
  category: "western",
  price: "9000",
  color: "pink",
  isBestSeller: true,
  description: "Luxury evening gown.",
  aosDelay: "0",
},
{
  id: 9,
  img: "/western/women3.jpg",
  title: "Minimal Casual Western Dress",
  slug: "minimal-casual-western-dress",
  rating: 2.0,
  category: "western",
  price: "1000",
  color: "white",
  isBestSeller: false,
  description: "Minimalist casual dress.",
  aosDelay: "0",
},
{
  id: 10,
  img: "/western/women4.jpg",
  title: "Off-Shoulder Summer Top",
  slug: "off-shoulder-summer-top",
  rating: 7.0,
  category: "western",
  price: "900",
  color: "white",
  isBestSeller: true,
  description: "Modern off-shoulder top.",
  aosDelay: "0",
},
{
  id: 11,
  img: "/western/women5.jpg",
  title: "Classic Western Button Shirt",
  slug: "classic-western-button-shirt",
  rating: 7.0,
  category: "western",
  price: "800",
  color: "white",
  isBestSeller: false,
  description: "Classic button-down western shirt.",
  aosDelay: "0",
},
{
  id: 12,
  img: "/western/women6.jpg",
  title: "Everyday Cotton Western Tee",
  slug: "everyday-cotton-western-tee",
  rating: 7.0,
  category: "western",
  price: "400",
  color: "white",
  isBestSeller: false,
  description: "Basic everyday western tee.",
  aosDelay: "0",
},

  {
  id: 13,
  img: "/goggles/women1.jpg",
  title: "UV Protection Casual Sunglasses",
  slug: "uv-protection-casual-sunglasses",
  rating: 7.0,
  category: "goggles",
  price: "800",
  color: "white",
  isBestSeller: false,
  description: "Stylish UV-protection sunglasses.",
  aosDelay: "0",
},
{
  id: 14,
  img: "/goggles/women2.webp",
  title: "Polarized Designer Sunglasses",
  slug: "polarized-designer-sunglasses",
  rating: 6.0,
  category: "goggles",
  price: "3000",
  color: "white",
  isBestSeller: false,
  description: "Premium polarized lenses.",
  aosDelay: "0",
},
{
  id: 15,
  img: "/goggles/women3.jpg",
  title: "Luxury Aviator Sunglasses",
  slug: "luxury-aviator-sunglasses",
  rating: 8.0,
  category: "goggles",
  price: "4000",
  color: "white",
  isBestSeller: true,
  description: "Luxury aviator-style goggles.",
  aosDelay: "0",
},
{
  id: 16,
  img: "/goggles/women4.webp",
  title: "Vintage Cat-Eye Sunglasses",
  slug: "vintage-cat-eye-sunglasses",
  rating: 7.0,
  category: "goggles",
  price: "2000",
  color: "white",
  isBestSeller: false,
  description: "Classic cat-eye goggles.",
  aosDelay: "0",
},
{
  id: 17,
  img: "/goggles/women5.png",
  title: "Sporty Wrap-Around Goggles",
  slug: "sporty-wrap-around-goggles",
  rating: 7.0,
  category: "goggles",
  price: "1000",
  color: "white",
  isBestSeller: false,
  description: "Sporty wrap-around goggles.",
  aosDelay: "0",
},
{
  id: 18,
  img: "/goggles/women6.jpg",
  title: "Oversized Square Frame Sunglasses",
  slug: "oversized-square-frame-sunglasses",
  rating: 7.0,
  category: "goggles",
  price: "2100",
  color: "white",
  isBestSeller: false,
  description: "Trendy oversized square frames.",
  aosDelay: "0",
},

  {
  id: 19,
  img: "/printedtshirts/Img19.jpg",
  title: "Artistic Graphic Print T-Shirt",
  slug: "artistic-graphic-print-tshirt",
  rating: 7.0,
  category: "printedtshirts",
  price: "800",
  color: "white",
  isBestSeller: true,
  description: "Artistic graphic print t-shirt. High-definition printing technology ensures the colors stay vibrant after many washes.",
  aosDelay: "0",
},
{
  id: 20,
  img: "/printedtshirts/Img20.jpg",
  title: "Abstract Pattern Print Tee",
  slug: "abstract-pattern-print-tee",
  rating: 7.0,
  category: "printedtshirts",
  price: "500",
  color: "white",
  isBestSeller: false,
  description: "Abstract pattern t-shirt for a unique look. Soft blend fabric provides a flattering fit for all body types.",
  aosDelay: "0",
},
{
  id: 21,
  img: "/printedtshirts/Img21.jpg",
  title: "Casual Lightweight Print T-Shirt",
  slug: "casual-lightweight-print-tshirt",
  rating: 7.0,
  category: "printedtshirts",
  price: "300",
  color: "white",
  isBestSeller: false,
  description: "Affordable casual print tee. Lightweight and breathable, making it a great choice for loungewear.",
  aosDelay: "0",
},
{
  id: 22,
  img: "/printedtshirts/Img22.jpg",
  title: "Inspirational Quote Print Tee",
  slug: "inspirational-quote-print-tee",
  rating: 4.0,
  category: "printedtshirts",
  price: "900",
  color: "white",
  isBestSeller: false,
  description: "Inspirational quote printed tee. Made from sustainable cotton with a focus on ethical manufacturing.",
  aosDelay: "0",
},
{
  id: 23,
  img: "/printedtshirts/Img23.jpg",
  title: "Floral Summer Print T-Shirt",
  slug: "floral-summer-print-tshirt",
  rating: 6.0,
  category: "printedtshirts",
  price: "870",
  color: "white",
  isBestSeller: false,
  description: "Floral print summer t-shirt. Adds a touch of femininity to your casual denim outfit.",
  aosDelay: "0",
},
{
  id: 24,
  img: "/printedtshirts/Img24.jpg",
  title: "Pop Art Printed T-Shirt",
  slug: "pop-art-printed-tshirt",
  rating: 7.0,
  category: "printedtshirts",
  price: "400",
  color: "white",
  isBestSeller: false,
  description: "Modern pop-art printed t-shirt. Bold colors and a relaxed neck design for a cool, youthful vibe.",
  aosDelay: "0",
},
{
  id: 25,
  img: "/fashiontshirt/Img25.jpg",
  title: "Ribbed Fitted Fashion T-Shirt",
  slug: "ribbed-fitted-fashion-tshirt",
  rating: 7.0,
  category: "fashiontshirt",
  price: "500",
  color: "white",
  isBestSeller: false,
  description: "High-fashion fitted t-shirt. Designed with a unique ribbed texture that elevates the standard tee.",
  aosDelay: "0",
},
{
  id: 26,
  img: "/fashiontshirt/Img26.jpg",
  title: "Classic Crew Neck Fashion T-Shirt",
  slug: "classic-crew-neck-fashion-tshirt",
  rating: 7.0,
  category: "fashiontshirt",
  price: "300",
  color: "white",
  isBestSeller: false,
  description: "Budget-friendly fashion tee. Simple, clean lines and a classic crew neck for everyday versatility.",
  aosDelay: "0",
},
{
  id: 27,
  img: "/fashiontshirt/Img27.jpg",
  title: "Moisture Wicking Fashion T-Shirt",
  slug: "moisture-wicking-fashion-tshirt",
  rating: 7.0,
  category: "fashiontshirt",
  price: "300",
  color: "white",
  isBestSeller: false,
  description: "Soft-touch fashion t-shirt. Excellent moisture-wicking properties keep you dry and comfortable.",
  aosDelay: "0",
},
{
  id: 28,
  img: "/fashiontshirt/Img28.jpg",
  title: "V-Neck Slim Fit Fashion T-Shirt",
  slug: "v-neck-slim-fit-fashion-tshirt",
  rating: 7.0,
  category: "fashiontshirt",
  price: "600",
  color: "white",
  isBestSeller: false,
  description: "V-neck fashion t-shirt with a slimming silhouette. Great for layering under jackets or cardigans.",
  aosDelay: "0",
},
{
  id: 29,
  img: "/fashiontshirt/Img29.jpg",
  title: "Streetwear Fashion Tee",
  slug: "streetwear-fashion-tee",
  rating: 7.0,
  category: "fashiontshirt",
  price: "900",
  color: "white",
  isBestSeller: true,
  description: "Premium oversized fashion tee. Made from heavyweight cotton for that high-end streetwear look.",
  aosDelay: "0",
},
{
  id: 30,
  img: "/fashiontshirt/Img30.jpg",
  title: "Trendy Top Fashion T-Shirt",
  slug: "trendy-top-fashion-tshirt",
  rating: 7.0,
  category: "fashiontshirt",
  price: "200",
  color: "white",
  isBestSeller: false,
  description: "Basic crop-top fashion tee. A trendy choice for pairing with high-waisted skirts or pants.",
  aosDelay: "0",
},
{
  id: 31,
  img: "/kids/Img31.jpg",
  title: "Boys Cotton Polo T-Shirt",
  slug: "boys-polo-tee",
  rating: 4.5,
  category: "kids",
  subCategory: "boys",
  price: "899",
  color: "Blue",
  isBestSeller: false,
  description: "Smart and classic polo shirt for boys. Breathable pique cotton fabric with a ribbed collar for a sharp look.",
  aosDelay: "0",
},
{
  id: 32,
  img: "/kids/Img32.jpg",
  title: "Boys Graphic Print Tee",
  slug: "boys-graphic-tee",
  rating: 4.2,
  category: "kids",
  subCategory: "boys",
  price: "599",
  color: "Yellow",
  isBestSeller: false,
  description: "Fun and vibrant graphic t-shirt for active boys. Soft fabric ensures no irritation during playtime.",
  aosDelay: "100",
},
{
  id: 33,
  img: "/kids/Img33.jpg",
  title: "Boys Denim Jogger Pants",
  slug: "boys-denim-joggers",
  rating: 4.7,
  category: "kids",
  subCategory: "boys",
  price: "1299",
  color: "Dark Blue",
  isBestSeller: true,
  description: "Comfortable denim joggers with an elasticated waistband. Combines the look of jeans with the comfort of track pants.",
  aosDelay: "200",
},
{
  id: 34,
  img: "/kids/Img34.jpg",
  title: "Boys Striped Summer Shirt",
  slug: "boys-striped-shirt",
  rating: 4.4,
  category: "kids",
  subCategory: "boys",
  price: "999",
  color: "White/Green",
  isBestSeller: false,
  description: "Lightweight summer shirt featuring cool stripes. Perfect for family outings and holiday trips.",
  aosDelay: "300",
},
{
  id: 35,
  img: "/kids/Img35.jpg",
  title: "Boys Hooded Sweatshirt",
  slug: "boys-hoodie",
  rating: 4.8,
  category: "kids",
  subCategory: "boys",
  price: "1599",
  color: "Grey",
  isBestSeller: true,
  description: "Cozy grey hoodie for chilly days. Features a soft fleece lining and a spacious kangaroo pocket.",
  aosDelay: "400",
},
{
  id: 36,
  img: "/kids/Img36.jpg",
  title: "Boys Casual Shorts",
  slug: "boys-casual-shorts",
  rating: 4.3,
  category: "kids",
  subCategory: "boys",
  price: "699",
  color: "Red",
  isBestSeller: false,
  description: "Bright red cotton shorts. Durable fabric that stands up to all-day running and climbing.",
  aosDelay: "500",
},

{
  id: 37,
  img: "/kids/Img37.jpg",
  title: "Girls Floral Summer Dress",
  slug: "girls-floral-dress",
  rating: 4.8,
  category: "kids",
  subCategory: "girls",
  price: "1299",
  color: "Pink",
  isBestSeller: true,
  description: "Beautiful pink floral dress for girls. Features a flared hem and soft inner lining for a princess-like feel.",
  aosDelay: "0",
},
{
  id: 38,
  img: "/kids/Img38.jpg",
  title: "Girls Embroidered Top",
  slug: "girls-embroidered-top",
  rating: 4.6,
  category: "kids",
  subCategory: "girls",
  price: "899",
  color: "White",
  isBestSeller: false,
  description: "Delicate white top with colorful embroidery on the shoulders. Adds a sweet and stylish touch to any outfit.",
  aosDelay: "100",
},
{
  id: 39,
  img: "/kids/Img39.jpg",
  title: "Girls Denim Skirt",
  slug: "girls-denim-skirt",
  rating: 4.4,
  category: "kids",
  subCategory: "girls",
  price: "999",
  color: "Light Blue",
  isBestSeller: false,
  description: "Trendy light blue denim skirt. Features an adjustable waistband to ensure the perfect fit as they grow.",
  aosDelay: "200",
},
{
  id: 40,
  img: "/kids/Img40.jpg",
  title: "Girls Cotton Leggings",
  slug: "girls-cotton-leggings",
  rating: 4.5,
  category: "kids",
  subCategory: "girls",
  price: "499",
  color: "Purple",
  isBestSeller: false,
  description: "Super-stretchy purple leggings. Great for pairing with tunics or wearing under dresses for extra coverage.",
  aosDelay: "300",
},
{
  id: 41,
  img: "/kids/Img41.jpg",
  title: "Girls Party Wear Gown",
  slug: "girls-party-gown",
  rating: 5.0,
  category: "kids",
  subCategory: "girls",
  price: "2499",
  color: "Red",
  isBestSeller: true,
  description: "Stunning red gown for special parties. Layers of tulle create a voluminous look that's perfect for birthdays.",
  aosDelay: "400",
},
{
  id: 42,
  img: "/kids/Img42.jpg",
  title: "Girls Casual Graphic Tee",
  slug: "girls-graphic-tee",
  rating: 4.3,
  category: "kids",
  subCategory: "girls",
  price: "599",
  color: "Peach",
  isBestSeller: false,
  description: "Adorable peach t-shirt with a cute graphic. Soft cotton-rich fabric keeps them comfy all day long.",
  aosDelay: "500",
},
{
  id: 43,
  img: "/men/Img43.jpg",
  title: "Men's Slim Fit Denim",
  slug: "mens-slim-denim",
  rating: 4.6,
  category: "men",
  price: "2499",
  color: "Indigo",
  isBestSeller: true,
  description: "Classic indigo slim-fit jeans. Features a hint of stretch for movement and a timeless five-pocket design.",
  aosDelay: "0",
},
{
  id: 44,
  img: "/men/Img44.jpg",
  title: "Men's Casual Linen Shirt",
  slug: "mens-linen-shirt",
  rating: 4.4,
  category: "men",
  price: "1899",
  color: "White",
  isBestSeller: false,
  description: "Breathable white linen shirt for men. Keeps you cool in hot weather while maintaining a sharp, relaxed aesthetic.",
  aosDelay: "100",
},
{
  id: 45,
  img: "/men/Img45.jpg",
  title: "Men's Graphic Cotton Tee",
  slug: "mens-graphic-tee",
  rating: 4.2,
  category: "men",
  price: "799",
  color: "Black",
  isBestSeller: false,
  description: "Edgy black graphic t-shirt. High-quality screen print on 100% combed cotton for ultimate comfort.",
  aosDelay: "200",
},
{
  id: 46,
  img: "/men/Img46.jpg",
  title: "Men's Chino Shorts",
  slug: "mens-chino-shorts",
  rating: 4.5,
  category: "men",
  price: "1299",
  color: "Khaki",
  isBestSeller: false,
  description: "Classic khaki shorts for a clean weekend look. Durable twill fabric that gets softer with every wash.",
  aosDelay: "300",
},
{
  id: 47,
  img: "/men/Img47.jpg",
  title: "Men's Bomber Jacket",
  slug: "mens-bomber-jacket",
  rating: 4.8,
  category: "men",
  price: "3499",
  color: "Olive Green",
  isBestSeller: true,
  description: "Stylish olive green bomber jacket. Lightweight yet warm, making it the perfect layering piece for transitional weather.",
  aosDelay: "400",
},
{
  id: 48,
  img: "/men/Img48.jpg",
  title: "Men's Formal Oxford Shirt",
  slug: "mens-formal-shirt",
  rating: 4.7,
  category: "men",
  price: "2199",
  color: "Light Blue",
  isBestSeller: false,
  description: "Premium light blue Oxford shirt. Features a classic button-down collar and a crisp finish for professional settings.",
  aosDelay: "500",
},
{
  id: 49,
  img: "/electronics/Img49.jpg",
  title: "Smartphone",
  slug: "smartphone",
  rating: 4.5,
  category: "electronics",
  price: "25000",
  color: "black",
  isBestSeller: true,
  description: "Latest generation smartphone with a high-resolution AMOLED display and a multi-lens camera system for professional-grade photos.",
  aosDelay: "200",
},
{
  id: 50,
  img: "/electronics/Img50.jpg",
  title: "Laptop",
  slug: "laptop",
  rating: 4.8,
  category: "electronics",
  price: "65000",
  color: "silver",
  isBestSeller: true,
  description: "High-performance silver laptop featuring a powerful processor and ultra-fast SSD. Ideal for professionals and students alike.",
  aosDelay: "400",
},
{
  id: 51,
  img: "/electronics/Img51.jpg",
  title: "Wireless Headphones",
  slug: "wireless-headphones",
  rating: 4.3,
  category: "electronics",
  price: "3000",
  color: "blue",
  isBestSeller: false,
  description: "Immersive blue wireless headphones with noise-cancellation technology. Enjoy up to 20 hours of crystal-clear playback on a single charge.",
  aosDelay: "600",
},
{
  id: 52,
  img: "/electronics/Img52.webp",
  title: "Smart Watch",
  slug: "smart-watch",
  rating: 4.6,
  category: "electronics",
  price: "5000",
  color: "black",
  isBestSeller: false,
  description: "Advanced black smartwatch with fitness tracking, heart rate monitoring, and smartphone notifications. Waterproof design for active lifestyles.",
  aosDelay: "800",
},
{
  id: 53,
  img: "/electronics/Img53.webp",
  title: "Bluetooth Speaker",
  slug: "bluetooth-speaker",
  rating: 4.4,
  category: "electronics",
  price: "2500",
  color: "red",
  isBestSeller: false,
  description: "Portable red bluetooth speaker with powerful bass and long battery life. Perfect for outdoor parties and home entertainment.",
  aosDelay: "1000",
}
];



export function getAllProducts(){
    return products;
}

export function getProductsByCategory(categoryName) {
  return products.filter(
    (product) => product.category === categoryName
  );
}

export function getProductById(id){
    return products.find( p => p.id === Number(id));
}